packages:
  - web

catalog:
  "@eslint/js": ^10.0.1
  comlink: ^4.4.2
  concurrently: ^10.0.3
  eslint: ^10.5.0
  eslint-config-prettier: ^10.1.8
  globals: ^17.6.0
  lit: ^3.3.2
  prettier: 3.8.4
  vite: ^8.0.12
